### PR TITLE
Keep the player in the viewport

### PR DESCRIPTION
**Pull request by pugson**

### CODE REVIEW

**Comment by sarahball** [comment]
This doesn't work due to the rather patchy way the iframe is set up to be responsive. I had it set to viewport measurements but it still goes over. Switched to percentages cause it's a teeny bit more supported.

**Comment by pugson** [comment]
It works fine with YouTube. The player takes up the remaining space of the window and the video is centered and scaled to fit.

See proof:
screen shot 2018-01-05 at 12 29 15 am

**Comment by sarahball** [comment]
Yeah...my first goal was to try to keep it at the same dimensions but center the frame it's in, to ditch the black border. Couldn't sort that quickly enough.

Next thought was to leave some room at the bottom for a social share down the line, so I left it as is.

I assumed people on desktop would resize the window to fit the video automatically. (It's not mobile responsive yet.) Maybe not?

Another option is to make the viewport fixed and leave it up to users to go full screen. (Just thinking out loud now @pugson sorry 😄 )

I just really don't like the way the black looks 🙈  Maybe do it your way and switch to a dark theme?

**Comment by pugson** [comment]
This calls for a custom YouTube player https://github.com/sampotts/plyr

**Comment by sarahball** [comment]
Oh snaaap! That looks amazing.

Leaving this PR open for now cause I know I can do better if I give it a bit of thought 😄  Thank you @pugson! ✨

**Comment by pugson** [comment]
For anyone reading this — come join us at [wip.chat](https://wip.chat) 🚧

**Pull request merged**
